---
- name: Set up swap file for droplet
  hosts: "*drop*"
  vars:
    - swap_file_path: /root/swapfile
    - swap_file_size: 1GB
  gather_facts: False

  tasks:
    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }}
               creates="{{ swap_file_path }}"
      tags:
        - swap.file.create
    - name: Change swap file permissions
      file: path="{{ swap_file_path }}"
            owner=root
            group=root
            mode=0600
      tags:
        - swap.file.permissions
    - name: Check swap file type
      command: file {{ swap_file_path }}
      register: swapfile
      tags:
        - swap.file.mkswap
    - name: Make swap file
      command: "sudo mkswap {{ swap_file_path }}"
      when: swapfile.stdout.find('swap file') == -1
      tags:
        - swap.file.mkswap
    - name: Write swap entry in fstab
      mount: name=none
             src={{ swap_file_path }}
             fstype=swap
             opts=sw
             passno=0
             dump=0
             state=present
      tags:
        - swap.fstab
    - name: Mount swap
      command: "swapon {{ swap_file_path }}"
      tags:
        - swap.file.swampon
